class PickListValuesAssociationsResponseHandler{

}
export {
	PickListValuesAssociationsResponseHandler as MasterModel,
	PickListValuesAssociationsResponseHandler as PickListValuesAssociationsResponseHandler
}
